<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{B4D68D82-7902-4117-A6EB-06BED7FDEA32}</ProjectGuid>
    <OutputType>Library</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>AddInGost</RootNamespace>
    <AssemblyName>AddInGost</AssemblyName>
    <TargetFrameworkVersion>v4.5.2</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="SolidworksBoardData">
      <HintPath>..\..\..\EPDM_AddInGOST\SolidworksBoardData.dll</HintPath>
    </Reference>
    <Reference Include="SolidworksNotes">
      <HintPath>..\..\..\EPDM_AddInGOST\SolidworksNotes.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="AbstractCommandGroup.cs" />
    <Compile Include="DrawingCommandGroup.cs" />
    <Compile Include="GostAddIn.cs" />
    <Compile Include="GostCommandManager.cs" />
    <Compile Include="OpenAssemblyXMLDialog.cs" />
    <Compile Include="PositionSpecification\AbstractPositions.cs" />
    <Compile Include="PositionSpecification\AutomaticalPositionSpecification.cs" />
    <Compile Include="PositionSpecification\ManualPositionSpecification.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\Annotation.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\AssemblyDoc.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\BalloonOptions.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\CommandGroup.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\CommandManager.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\Component2.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\Configuration.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\DAssemblyDocEvents.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\DAssemblyDocEvents_Event.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\DDrawingDocEvents.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\DDrawingDocEvents_Event.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\DDrawingDocEvents_UserSelectionPostNotifyEventHandler.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\DModelViewEvents.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\DModelViewEvents_Event.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\DMouseEvents.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\DMouseEvents_Event.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\DMouseEvents_MouseRBtnDownNotifyEventHandler.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\DrawingComponent.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\DrawingDoc.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\DSldWorksEvents.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\DSldWorksEvents_Event.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\Entity.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\IAnnotation.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\IAssemblyDoc.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\IBalloonOptions.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\ICommandGroup.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\ICommandManager.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\IComponent2.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\IConfiguration.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\IDrawingComponent.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\IDrawingDoc.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\IEntity.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\IModelDoc2.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\IModelDocExtension.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\IModelView.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\IMouse.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\INote.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\ISelectionMgr.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\ISheet.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\ISldWorks.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\IView.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\ModelDoc2.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\ModelDocExtension.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\ModelView.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\Mouse.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\Note.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\SelectionMgr.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\Sheet.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\SldWorks.cs" />
    <Compile Include="SolidWorks\Interop\sldworks\View.cs" />
    <Compile Include="SolidWorks\Interop\swpublished\ISwAddin.cs" />
    <Compile Include="TextDocCommandGroup.cs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\CadBoardData\CadBoardData.csproj">
      <Project>{a61842e8-dc11-4a85-9184-ef40ad760388}</Project>
      <Name>CadBoardData</Name>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Reports\ReportsESKD\ReportsESKD.csproj">
      <Project>{04c37611-52f9-4a28-b7a5-787f241d083a}</Project>
      <Name>ReportsESKD</Name>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Reports\ReportsOutput\ReportsOutput.csproj">
      <Project>{4b29eb96-ef44-4be4-a825-65ff18e3c19f}</Project>
      <Name>ReportsOutput</Name>
    </ProjectReference>
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>